name: bible_quiz
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  flutter_animate: ^4.5.2
  confetti: ^0.8.0
  audioplayers: ^6.4.0
  lucide_icons: ^0.257.0
  google_fonts: ^6.2.1
  line_icons: ^2.0.3
  path_provider: ^2.1.5
  google_mobile_ads: ^6.0.0
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/sounds/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
